"""create posts table

Revision ID: d9023b7c0b32
Revises: 
Create Date: 2026-08-17 00:20:02.713759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9023b7c0b32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('_prisma_migrations')
    op.drop_table('trending_audio')
    op.add_column('posts', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('posts', sa.Column('caption', sa.Text(), nullable=False))
    op.alter_column('posts', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('posts', 'status',
               existing_type=postgresql.ENUM('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'AUTO_REJECTED', 'PUBLISHED', name='PostState'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text('\'PENDING_APPROVAL\'::"PostState"'))
    op.alter_column('posts', 'media_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=True)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.drop_constraint(op.f('posts_event_id_fkey'), 'posts', type_='foreignkey')
    op.drop_column('posts', 'event_id')
    op.drop_column('posts', 'applied_prompt')
    op.drop_column('posts', 'last_prompted_at')
    op.drop_column('posts', 'scheduled_publish_time')
    op.drop_column('posts', 'generated_caption')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('generated_caption', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('scheduled_publish_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('last_prompted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('applied_prompt', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('posts_event_id_fkey'), 'posts', 'events', ['event_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.alter_column('posts', 'media_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('posts', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'AUTO_REJECTED', 'PUBLISHED', name='PostState'),
               existing_nullable=False,
               existing_server_default=sa.text('\'PENDING_APPROVAL\'::"PostState"'))
    op.alter_column('posts', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('posts', 'caption')
    op.drop_column('posts', 'title')
    op.create_table('trending_audio',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(length=50), server_default=sa.text("'PK'::character varying"), autoincrement=False, nullable=False),
    sa.Column('track_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('artist', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('audio_meta_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('trending_audio_pkey'))
    )
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('FESTIVAL', 'CAMPAIGN', 'REGULAR', name='EventType'), server_default=sa.text('\'REGULAR\'::"EventType"'), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('custom_prompt_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    # ### end Alembic commands ###
